version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cinema_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: cinema_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app  # <-- Ось це робить Live Sync твого коду з Docker

# Це має бути притиснуто до самого лівого краю (без пробілів)
volumes:
  pgdata: